name: Build Static Wget with SSL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 安装依赖环境
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3 unzip zlib1g-dev file

      - name: 下载并解压 OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/18.06.5/targets/mediatek/mt7622/openwrt-sdk-18.06.5-mediatek-mt7622_gcc-7.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-*/ sdk

      - name: 添加 wget 源码包
        run: |
          mkdir -p sdk/package/mywget
          cd sdk/package/mywget
          wget https://downloads.openwrt.org/releases/18.06.5/packages/aarch64_cortex-a53/base/wget_1.19.5-1_aarch64_cortex-a53.ipk
          # 提取源码版本（原始 Makefile 在 base feeds 中找不到了，所以我们重写）
          cd ../..
          cat <<EOF > sdk/package/mywget/Makefile
include \$(TOPDIR)/rules.mk

PKG_NAME:=wget
PKG_VERSION:=1.19.5
PKG_RELEASE:=1

PKG_SOURCE:=wget-\$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=@GNU/wget
PKG_HASH:=dd2b1f56b14ed4d5dca2a50d80e1d6a0f0f43b366c6d020e2d0b7f72a7c2eaab

PKG_BUILD_DIR:=\$(BUILD_DIR)/wget-\$(PKG_VERSION)
PKG_LICENSE:=GPL-3.0-or-later
PKG_CPE_ID:=cpe:/a:gnu:wget

include \$(INCLUDE_DIR)/package.mk

define Package/wget
  SECTION:=net
  CATEGORY:=Network
  TITLE:=Free utility for non-interactive download of files from the Web
  DEPENDS:=+libopenssl
endef

define Package/wget/description
 Wget is a network utility to retrieve files from the Web using http and ftp.
endef

CONFIGURE_ARGS += \
	--enable-static --disable-shared \
	--with-ssl=openssl

define Build/Configure
	\$(call Build/Configure/Default)
endef

define Package/wget/install
	\$(INSTALL_DIR) \$(1)/usr/bin
	\$(INSTALL_BIN) \$(PKG_BUILD_DIR)/src/wget \$(1)/usr/bin/wget
endef

\$(eval \$(call BuildPackage,wget))
EOF

      - name: 编译 wget
        working-directory: ./sdk
        run: |
          make defconfig
          make package/mywget/compile V=s

      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: wget-static-ssl
          path: |
            sdk/build_dir/target-*/wget-*/src/wget
