name: Build Static Wget with SSL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses5-dev libssl-dev python3 unzip zlib1g-dev file

      - name: 下载 OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/18.06.5/targets/mediatek/mt7622/openwrt-sdk-18.06.5-mediatek-mt7622_gcc-7.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: 初始化 feeds 并安装 wget
        working-directory: ./sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install wget

      - name: 修改 wget 为静态编译 + 启用 SSL
        run: |
          WGET_MAKEFILE=$(find sdk/feeds/packages -type f -path "*/wget/Makefile" | head -n 1)
          echo "修改文件: $WGET_MAKEFILE"
          sed -i '/CONFIGURE_ARGS/ a\ \t--enable-static --disable-shared' "$WGET_MAKEFILE"
          echo 'TARGET_CFLAGS += -static' >> "$WGET_MAKEFILE"

      - name: 编译 wget
        working-directory: ./sdk
        run: |
          echo "CONFIG_PACKAGE_wget=y" >> .config
          make defconfig
          make package/wget/compile V=s

      - name: 上传静态 wget
        uses: actions/upload-artifact@v4
        with:
          name: wget-static
          path: |
            sdk/build_dir/target-*/wget-*/src/wget
