name: Build Static Wget with SSL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 安装依赖
        run: sudo apt update && sudo apt install -y build-essential libncurses5-dev libssl-dev wget

      - name: 下载并解压 SDK
        run: |
          wget https://downloads.openwrt.org/releases/18.06.5/targets/mediatek/mt7622/openwrt-sdk-18.06.5-mediatek-mt7622_gcc-7.3.0_musl.Linux-x86_64.tar.xz
          tar -xf *.tar.xz
          SDK_DIR=$(tar -tf *.tar.xz | head -n1 | cut -d/ -f1)
          mv "$SDK_DIR" sdk

      - name: 添加静态 + SSL 选项
        working-directory: ./sdk
        run: |
          echo 'CONFIG_PACKAGE_wget=y' >> .config
          echo 'CONFIG_WGET=y' >> .config
          echo 'CONFIG_WGET_OPENSSL=y' >> .config
          echo 'CONFIG_WGET_STATIC=y' >> .config || true
          make defconfig

      - name: 编译 wget
        working-directory: ./sdk
        run: make package/wget/compile V=s

      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: wget-ssl-static
          path: sdk/build_dir/target-*/wget-*/src/wget
