name: Build Static Wget with SSL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 初始化环境
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3 unzip zlib1g-dev file

      - name: 下载并解压 OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/18.06.5/targets/mediatek/mt7622/openwrt-sdk-18.06.5-mediatek-mt7622_gcc-7.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-*.tar.xz
          rm -rf sdk
          mv openwrt-sdk-* sdk

      - name: 初始化 Feeds 并安装 wget
        working-directory: ./sdk
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install wget

      - name: 修改 wget Makefile 使其静态编译并启用 SSL
        working-directory: ./sdk/feeds/base/wget
        run: |
          sed -i '/CONFIGURE_ARGS/ a\ \t--enable-static --disable-shared' Makefile
          echo 'TARGET_CFLAGS += -static' >> Makefile

      - name: 编译 wget
        working-directory: ./sdk
        run: |
          make defconfig
          make package/feeds/base/wget/compile V=s

      - name: 上传编译好的 wget
        uses: actions/upload-artifact@v4
        with:
          name: wget-static
          path: |
            sdk/build_dir/target-*/wget-*/src/wget
